[package]
name = "bzf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "0.3.2"

[dependencies.crossterm]
version = "0.28.0"
features = ["events"]
